import Foundation

/// Every colour in the product, keyed by the token name `DESIGN.md` §2 uses.
///
/// This is a `CaseIterable` enum rather than an array of values on purpose. The parity test in
/// `DesignTokenParityTests` walks `allCases` to prove the code and the design document agree in
/// **both** directions, and `allCases` is generated by the compiler — so a colour cannot be added
/// here without the test seeing it. A hand-maintained `all` array would let a constant drift in
/// unnoticed, which is exactly the failure the test exists to catch.
///
/// Values only. Binding these to SwiftUI (`Color`, the asset catalogue, the authored light
/// appearance) belongs to the design-system item; this layer stays importable by anything,
/// including the router's tests, which have no UI framework.
public enum ColorToken: String, CaseIterable, Sendable {
    // Grounds and lines.
    case ground = "--ground"
    case panel = "--panel"
    case raised = "--raised"
    case raised2 = "--raised2"
    case line = "--line"
    case lineStrong = "--lineS"

    // Label tiers.
    case t1 = "--t1"
    case t2 = "--t2"
    case t3 = "--t3"
    case t4 = "--t4"

    // The four exclusive meanings.
    case accent = "--accent"
    case live = "--live"
    case attention = "--attn"
    case fail = "--fail"

    /// The base colour, always in canonical six-digit upper-case form.
    ///
    /// `DESIGN.md` writes the label tiers and lines as `#FFF`; three-digit and six-digit forms are
    /// the same colour, so the parity test expands both before comparing rather than treating
    /// `#FFF` and `#FFFFFF` as a drift.
    public var hex: String {
        switch self {
        case .ground: "#1E1E1E"
        case .panel: "#232326"
        case .raised: "#2C2C2E"
        case .raised2: "#3A3A3C"
        case .line, .lineStrong, .t1, .t2, .t3, .t4: "#FFFFFF"
        case .accent: "#0091FF"
        case .live: "#30D158"
        case .attention: "#FF9230"
        case .fail: "#FF4245"
        }
    }

    /// Alpha as a fraction. `DESIGN.md` states these as percentages (`@7.5%`).
    public var opacity: Double {
        switch self {
        case .line: 0.075
        case .lineStrong: 0.14
        case .t1: 1.0
        case .t2: 0.55
        case .t3: 0.50
        case .t4: 0.25
        default: 1.0
        }
    }

    /// Whether this colour may be used for anything other than its one stated meaning.
    ///
    /// The four indicator hues are exclusive by design: one amber dot in a menu bar only means
    /// something because nothing else in the app is allowed to be amber. Surfaces can assert
    /// against this rather than relying on review to catch a decorative use.
    public var isReservedMeaning: Bool {
        switch self {
        case .accent, .live, .attention, .fail: true
        default: false
        }
    }
}
