import Foundation
import Testing
@testable import RouterCore

/// The two JavaScript coercions a careful Swift port gets wrong by reaching for the obvious type.
///
/// Both of these were **live defects** in this branch, found by the out-of-family plan review and
/// confirmed against `src/control.ts` before being fixed. Each test below fails on the code that
/// was there: `projects` was tested with `asArray`, and `limit` was parsed with `Double.init`.
struct JSCoercionTests {
    // MARK: - B42 · `b.projects?.length` is a property read, not an array test

    @Test("a length-bearing non-array is truthy, so PATCH projects:\"x\" is stored rather than removed")
    func lengthTruthinessMatchesPropertyRead() {
        // A string has a `length`, so the reference stores it unchanged. `asArray` returns nil here,
        // which removed the member — the exact vector B42 names.
        #expect(JSONValue.string(JSString("x")).jsLengthIsTruthy)
        #expect(!JSONValue.string(JSString("")).jsLengthIsTruthy)

        #expect(JSONValue.array([.number(1)]).jsLengthIsTruthy)
        #expect(!JSONValue.array([]).jsLengthIsTruthy)

        // `{length: 3}` reads 3; an object without the member reads `undefined`.
        #expect(JSONValue.object([JSONMember(key: "length", value: .number(3))]).jsLengthIsTruthy)
        #expect(!JSONValue.object([JSONMember(key: "other", value: .number(3))]).jsLengthIsTruthy)
        #expect(!JSONValue.object([JSONMember(key: "length", value: .number(0))]).jsLengthIsTruthy)

        // Numbers, booleans and null carry no `length` property at all.
        #expect(!JSONValue.number(5).jsLengthIsTruthy)
        #expect(!JSONValue.bool(true).jsLengthIsTruthy)
        #expect(!JSONValue.null.jsLengthIsTruthy)
    }

    // MARK: - B46, B54 · `Number(x)` is not `Double(x)`

    @Test("Number() takes an empty string as 0 and trims whitespace, where Double yields nil")
    func numberCoercionMatchesECMAScript() {
        // The two inputs a query string actually delivers, and the two `Double.init` gets wrong.
        #expect(JSToNumber.number("") == 0)
        #expect(JSToNumber.number("   ") == 0)
        #expect(JSToNumber.number(" 12 ") == 12)
        #expect(Double("") == nil)
        #expect(Double(" 12 ") == nil)

        #expect(JSToNumber.number("abc").isNaN)
        #expect(JSToNumber.number("12abc").isNaN)
        #expect(JSToNumber.number("0x10") == 16)
        #expect(JSToNumber.number("-0x10").isNaN) // radix literals take no sign
        #expect(JSToNumber.number("1e3") == 1000)
        #expect(JSToNumber.number("1.") == 1)
        #expect(JSToNumber.number(".5") == 0.5)
        #expect(JSToNumber.number("Infinity").isInfinite)
        #expect(JSToNumber.number("-Infinity") == -Double.infinity)
        #expect(JSToNumber.number("-5") == -5)

        // Forms `Double` accepts and `Number` does not.
        #expect(JSToNumber.number("1_000").isNaN)
        #expect(JSToNumber.number("nan").isNaN)
        #expect(JSToNumber.number("inf").isNaN)
        #expect(JSToNumber.number("١٢").isNaN) // Arabic-Indic digits are not StrDecimalLiteral
    }

    // MARK: - N8 · `localeCompare`, pinned against Node's own output

    /// Generated by running `String.prototype.localeCompare` under Node on this machine. The point
    /// is the second group: for letters, ICU disagrees with a code-unit comparison in both
    /// directions, so a port that used `<` would rank tied registry rows the wrong way round.
    @Test("localeCompare matches Node for ISO timestamps and the letter cases code units get wrong")
    func localeCompareMatchesNode() {
        // ISO timestamps: ICU and code-unit agree, and this is the domain `updatedAt` carries.
        #expect(JSLocaleCompare.compare("2024-01-01T00:00:00.1Z", "2024-01-01T00:00:00.10Z") == 1)
        #expect(JSLocaleCompare.compare("2024-01-02", "20240102") == -1)
        #expect(JSLocaleCompare.compare("2024-1-1", "2024-01-01") == 1)
        #expect(JSLocaleCompare.compare("2024-01-01T00:00:00Z", "") == 1)
        #expect(JSLocaleCompare.compare("", "") == 0)

        // Letters: ICU orders by letter then by case, the reverse of code-unit order both times.
        #expect(JSLocaleCompare.compare("a", "B") == -1) // code units would say 1
        #expect(JSLocaleCompare.compare("A", "a") == 1) // code units would say -1
        #expect(JSLocaleCompare.compare("z", "ä") == 1) // code units would say -1
    }
}
