import Foundation
import Testing
@testable import RouterCore

/// Loads a committed parity vector file.
///
/// The vectors are generated by running the TypeScript router itself
/// (`scripts/parity/generate-vectors.mjs`), so what they record is what the reference does rather
/// than what anyone believed it does.
enum Vectors {
    static func load<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
        guard let url = Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Vectors")
            ?? Bundle.module.url(forResource: name, withExtension: "json")
        else {
            Issue.record("vector file \(name).json is missing — the corpus cannot be allowed to shrink silently")
            throw VectorError.missing(name)
        }
        return try JSONDecoder().decode(type, from: Data(contentsOf: url))
    }

    enum VectorError: Error { case missing(String) }
}

struct JSONRoundTripVectors: Decodable {
    struct Case: Decodable {
        let id: String
        let text: String
        let compact: String
        let pretty: String
    }

    let cases: [Case]
}

struct StringOrderingVectors: Decodable {
    struct Case: Decodable {
        let id: String
        let input: [String]
        let sorted: [String]
    }

    let cases: [Case]
}

@Suite("JSON parity with JSON.parse and JSON.stringify")
struct JSONParityTests {
    /// Compares **bytes**, never `String`s.
    ///
    /// This is not pedantry. Swift compares strings by canonical equivalence, so `"\u{00E9}"` and
    /// `"e\u{0301}"` are `==` — and the `canonical-equivalence` vector exists precisely because
    /// JavaScript keeps them as two distinct object keys. A `String`-based assertion would pass
    /// while the implementation had merged them and changed the digest.
    private func expectSameBytes(_ actual: String, _ expected: String, _ label: String) {
        let actualBytes = Array(actual.utf8)
        let expectedBytes = Array(expected.utf8)
        #expect(actualBytes == expectedBytes, "\(label): produced \(actual.debugDescription), expected \(expected.debugDescription)")
    }

    @Test("every document re-serialises to the bytes JSON.stringify produces")
    func compactRoundTrip() throws {
        let vectors = try Vectors.load("json-roundtrip", as: JSONRoundTripVectors.self)
        #expect(!vectors.cases.isEmpty)
        for testCase in vectors.cases {
            let value = try JSONParser.parse(testCase.text)
            expectSameBytes(JSStringify.compact(value), testCase.compact, "compact/\(testCase.id)")
        }
    }

    @Test("every document pretty-prints to the bytes JSON.stringify(v, null, 2) produces")
    func prettyRoundTrip() throws {
        let vectors = try Vectors.load("json-roundtrip", as: JSONRoundTripVectors.self)
        for testCase in vectors.cases {
            let value = try JSONParser.parse(testCase.text)
            expectSameBytes(JSStringify.prettyTwoSpace(value), testCase.pretty, "pretty/\(testCase.id)")
        }
    }

    @Test("string ordering follows UTF-16 code units, which is what the reference comparator does")
    func stringOrdering() throws {
        let vectors = try Vectors.load("string-ordering", as: StringOrderingVectors.self)
        for testCase in vectors.cases {
            let sorted = testCase.input.map { JSString($0) }.sorted()
            let expected = testCase.sorted.map { JSString($0) }
            let got = sorted.map { $0.string }
            #expect(sorted == expected, "\(testCase.id): got \(got), expected \(testCase.sorted)")
        }
    }

    /// The one case the whole `JSString` design exists for, asserted directly rather than only
    /// through a vector — an emoji leads with code unit `0xD83D`, below `0xE000`, so it sorts
    /// first; by Unicode scalar it would sort last.
    @Test("a supplementary character sorts before a private-use one")
    func utf16OrderingBeatsScalarOrdering() {
        let emoji = JSString("\u{1F600}")
        let privateUse = JSString("\u{E000}")
        #expect(emoji < privateUse)
        #expect(emoji.string.unicodeScalars.first!.value > privateUse.string.unicodeScalars.first!.value,
                "by scalar value the order is the other way round, which is the divergence being guarded")
    }

    /// Swift considers these two strings equal. JavaScript keeps them as separate keys, so
    /// `JSString` must too.
    @Test("canonically equivalent strings stay distinct")
    func canonicalEquivalenceIsNotEquality() {
        let precomposed = JSString("\u{00E9}")
        let decomposed = JSString("e\u{0301}")
        #expect(precomposed != decomposed)
        #expect(precomposed.string == decomposed.string, "Swift's String does treat them as equal — that is the trap")
    }

    @Test("a lone surrogate survives a parse and re-serialises escaped")
    func loneSurrogateSurvives() throws {
        let value = try JSONParser.parse("\"\\ud800\"")
        #expect(value.asString?.units == [0xD800])
        expectSameBytes(JSStringify.compact(value), "\"\\ud800\"", "lone surrogate")
    }

    @Test("array-index classification matches ToString(ToUint32(key)) == key")
    func arrayIndexPredicate() {
        #expect(JSString("0").arrayIndex == 0)
        #expect(JSString("4294967294").arrayIndex == 4_294_967_294)
        #expect(JSString("4294967295").arrayIndex == nil, "reserved as the maximum array length")
        #expect(JSString("01").arrayIndex == nil, "a leading zero never round-trips")
        #expect(JSString("-0").arrayIndex == nil)
        #expect(JSString("4294967296").arrayIndex == nil, "wraps to 0 and so does not round-trip")
        #expect(JSString("a").arrayIndex == nil)
        #expect(JSString("").arrayIndex == nil)
    }
}
