import Foundation

/// The sidebar's two named groups.
///
/// Sentence case, and stored that way rather than being upper-cased at render time.
/// `DESIGN.md` §3.2 is explicit that tracked uppercase is the loudest web tell and that the fix
/// is to *remove* it rather than re-track it — so there is no case transform anywhere in the
/// shell, and `ShellDestinationTests` asserts these literals.
public enum DestinationGroup: String, CaseIterable, Sendable {
    case running = "Running"
    case library = "Library"
}

/// Where a destination's badge count comes from, when it has one.
///
/// Modelled rather than left implicit because `DESIGN.md` §6 forbids displaying a number the system
/// has not observed, and the way that rule gets broken is by someone adding a plausible count to a
/// row. Every case here names a thing that is genuinely counted somewhere; a destination with no
/// such source has `nil`, and `ShellDestinationTests` fails if that ever stops being true for Skills.
///
/// **Two of the three are fields the router serves; the third is not, and that is deliberate.** M6's
/// inbox queue is held by the app itself, so its count is observed by the app rather than reported
/// by the router — which is a different provenance, not a weaker one. What §6 forbids is a figure
/// nobody observed at all (its example is a memory saving computed against a world the router never
/// runs). A count of the rows a surface is currently rendering is the most directly observed number
/// available, and `InboxBoardModel.waitingCount` derives it from the same array the list draws, so
/// the badge and the list cannot disagree.
public enum BadgeSource: String, CaseIterable, Sendable {
    /// Servers wanting a human decision — `MCPServer.needsAttention`.
    case serversNeedingAttention
    /// Servers nobody has ever called — `MCPServer.neverUsed`.
    case serversNeverUsed
    /// Items a paired phone has queued and nobody has acted on — the app's own inbox.
    case queuedFromPhone
}

/// The eight places the sidebar can take you.
///
/// A `CaseIterable` enum rather than an array, for the same reason `ColorToken` is one: `allCases`
/// is generated by the compiler, so a destination cannot be added without every exhaustive switch
/// over it failing to compile until it is handled. A hand-maintained list would let one drift in
/// unrendered.
public enum Destination: String, CaseIterable, Sendable, Identifiable {
    // Running.
    case activity
    case servers
    case skills
    // Library.
    case discover
    case inbox
    case evals
    case cleanup
    // Ungrouped.
    case settings

    public var id: String { rawValue }

    /// The label, and the window title while this destination is selected.
    ///
    /// `DESIGN.md` §3.7: the window title says what you are looking at, not the app's name.
    ///
    /// **`.evals` reads `Checks`, and the case name deliberately does not follow it.** M7 renamed
    /// this concept when it built the board — `MCPRouterKit/Checks/` holds `CheckModels`,
    /// `CheckCopy`, `CheckPresentation`, `ServerChecks` and `SkillChecks`, and `CheckCopy`'s
    /// user-facing strings are check vocabulary throughout — but the label kept saying `Evals`,
    /// which is the one word in the app that promises a grading verdict this product cannot
    /// produce (there is no eval runner anywhere in it). So this closes a rename that was already
    /// half-applied rather than introducing a name.
    ///
    /// The `rawValue`, the `iconName` and the deep-link slug stay `evals` on purpose: they are
    /// **identifiers**, persisted in frame restoration and used by the prototype's `?pane=evals`
    /// link, and `DESIGN.md` §6 governs words a user reads rather than keys a machine matches.
    /// Aligning them would break restoration for anyone who has already run the app and every mock
    /// link in `ORCHESTRATOR.md`, for no visible gain.
    public var title: String {
        switch self {
        case .activity: "Activity"
        case .servers: "Servers"
        case .skills: "Skills"
        case .discover: "Discover"
        case .inbox: "Inbox"
        case .evals: "Checks"
        case .cleanup: "Cleanup"
        case .settings: "Settings"
        }
    }

    /// The group this destination sits in. `nil` is the ungrouped tail, which is Settings alone.
    public var group: DestinationGroup? {
        switch self {
        case .activity, .servers, .skills: .running
        case .discover, .inbox, .evals, .cleanup: .library
        case .settings: nil
        }
    }

    /// The `⌘`-digit that selects this destination, where it has one.
    ///
    /// Settings has none because `DESIGN.md` §8 already binds it to `⌘,`; giving it a digit too
    /// would put two shortcuts on one command, which is how a menu bar starts teaching two
    /// different habits for the same thing.
    public var selectionDigit: Int? {
        switch self {
        case .activity: 1
        case .servers: 2
        case .skills: 3
        case .discover: 4
        case .inbox: 5
        case .evals: 6
        case .cleanup: 7
        case .settings: nil
        }
    }

    /// Where this destination's badge count comes from, or `nil` when it may not have one.
    ///
    /// **Skills is deliberately `nil`.** The prototype draws a badge on it and the control API
    /// serves no skills endpoint at all, so a count there would be invented.
    ///
    /// **Inbox was `nil` until M6 and is not any more.** The reason it was is recorded here because
    /// it is the reason it changed: Inbox means the phone's review queue (`DESIGN.md` §9), the
    /// router does not serve it, and until a surface actually held that queue there was nothing
    /// counting it. M6 builds the queue into the app, so the count is now an observation the app
    /// makes directly rather than a number nobody took. `heldChanges` is still not an inbox — it is
    /// one server's held tool-surface change, already counted by `needsAttention` on the Servers
    /// badge — and nothing here reads it.
    public var badgeSource: BadgeSource? {
        switch self {
        case .servers: .serversNeedingAttention
        case .cleanup: .serversNeverUsed
        case .inbox: .queuedFromPhone
        case .activity, .skills, .discover, .evals, .settings: nil
        }
    }

    /// The raw value of the `Icon` case this destination draws.
    ///
    /// A string rather than the `Icon` type itself because `Icon` lives in `MCPRouterUI` and this
    /// module must stay free of UI frameworks (`SWIFT_PRACTICES.md` §8). `ShellIconTests` in the
    /// UI module asserts every one of these resolves to a real case, so the indirection cannot
    /// silently point at nothing.
    public var iconName: String {
        switch self {
        case .activity: "activity"
        case .servers: "servers"
        case .skills: "skills"
        case .discover: "discover"
        case .inbox: "inbox"
        case .evals: "evals"
        case .cleanup: "cleanup"
        case .settings: "settings"
        }
    }

    /// The destinations in sidebar order, which is declaration order.
    public static var ordered: [Destination] { allCases }

    /// The destinations in one group, in order.
    public static func inGroup(_ group: DestinationGroup?) -> [Destination] {
        ordered.filter { $0.group == group }
    }

    /// What a stored destination restores to when this build no longer has it.
    ///
    /// `DESIGN.md` has no rule for this, but a blank pane does: restoring a name this version does
    /// not know must land somewhere real rather than rendering nothing. Activity is the first
    /// destination and the one that needs no selection to be meaningful.
    public static let fallback: Destination = .activity

    /// Restores a stored raw value, falling back rather than failing.
    public static func restoring(_ storedRawValue: String?) -> Destination {
        guard let storedRawValue, let destination = Destination(rawValue: storedRawValue) else {
            return fallback
        }
        return destination
    }
}
