import Foundation

/// The sidebar's two named groups.
///
/// Sentence case, and stored that way rather than being upper-cased at render time.
/// `DESIGN.md` §3.2 is explicit that tracked uppercase is the loudest web tell and that the fix
/// is to *remove* it rather than re-track it — so there is no case transform anywhere in the
/// shell, and `ShellDestinationTests` asserts these literals.
public enum DestinationGroup: String, CaseIterable, Sendable {
    case running = "Running"
    case library = "Library"
}

/// Where a destination's badge count comes from, when it has one.
///
/// Modelled rather than left implicit because `DESIGN.md` §6 forbids displaying a number the system
/// has not observed, and the way that rule gets broken is by someone adding a plausible count to a
/// row. Every case here names a thing that is genuinely counted somewhere; a destination with no
/// such source has `nil`, and `ShellDestinationTests` fails if that ever stops being true for Skills.
///
/// **Two of the three are fields the router serves; the third is not, and that is deliberate.** M6's
/// inbox queue is held by the app itself, so its count is observed by the app rather than reported
/// by the router — which is a different provenance, not a weaker one. What §6 forbids is a figure
/// nobody observed at all (its example is a memory saving computed against a world the router never
/// runs). A count of the rows a surface is currently rendering is the most directly observed number
/// available, and `InboxBoardModel.waitingCount` derives it from the same array the list draws, so
/// the badge and the list cannot disagree.
public enum BadgeSource: String, CaseIterable, Sendable {
    /// Servers wanting a human decision — `MCPServer.needsAttention`.
    case serversNeedingAttention
    /// Servers nobody has ever called — `MCPServer.neverUsed`.
    case serversNeverUsed
    /// Items a paired phone has queued and nobody has acted on — the app's own inbox.
    case queuedFromPhone
}

/// The seven places the sidebar can take you.
///
/// **It was eight until M15.** `settings` was the ungrouped tail, and it is now a `Settings` scene
/// of its own rather than a board in this list — which is what macOS does, and what the console
/// mock draws. Removing the case rather than leaving it unrendered is what makes `group`
/// non-optional below and what makes a stored `"settings"` restore to Activity.
///
/// A `CaseIterable` enum rather than an array, for the same reason `ColorToken` is one: `allCases`
/// is generated by the compiler, so a destination cannot be added without every exhaustive switch
/// over it failing to compile until it is handled. A hand-maintained list would let one drift in
/// unrendered.
public enum Destination: String, CaseIterable, Sendable, Identifiable {
    // Running.
    case activity
    case servers
    case skills
    // Library.
    case discover
    case inbox
    case evals
    case cleanup

    public var id: String { rawValue }

    /// The label, and the window title while this destination is selected.
    ///
    /// `DESIGN.md` §3.7: the window title says what you are looking at, not the app's name.
    ///
    /// **`.evals` reads `Checks`, and the case name deliberately does not follow it.** M7 renamed
    /// this concept when it built the board — `MCPRouterKit/Checks/` holds `CheckModels`,
    /// `CheckCopy`, `CheckPresentation`, `ServerChecks` and `SkillChecks`, and `CheckCopy`'s
    /// user-facing strings are check vocabulary throughout — but the label kept saying `Evals`,
    /// which is the one word in the app that promises a grading verdict this product cannot
    /// produce (there is no eval runner anywhere in it). So this closes a rename that was already
    /// half-applied rather than introducing a name.
    ///
    /// The `rawValue`, the `iconName` and the deep-link slug stay `evals` on purpose: they are
    /// **identifiers**, persisted in frame restoration and used by the prototype's `?pane=evals`
    /// link, and `DESIGN.md` §6 governs words a user reads rather than keys a machine matches.
    /// Aligning them would break restoration for anyone who has already run the app and every mock
    /// link in `ORCHESTRATOR.md`, for no visible gain.
    public var title: String {
        switch self {
        case .activity: "Activity"
        case .servers: "Servers"
        case .skills: "Skills"
        case .discover: "Discover"
        case .inbox: "Inbox"
        case .evals: "Checks"
        case .cleanup: "Cleanup"
        }
    }

    /// The group this destination sits in.
    ///
    /// **Non-optional since M15.** `nil` used to mean the ungrouped tail, which was Settings alone;
    /// Settings is a window now, so every destination is in a named group and the optionality had
    /// exactly one inhabitant left. Dead optionality is not left behind for M22 to inherit — it
    /// reworks these groups next.
    public var group: DestinationGroup {
        switch self {
        case .activity, .servers, .skills: .running
        case .discover, .inbox, .evals, .cleanup: .library
        }
    }

    /// The `⌘`-digit that selects this destination.
    ///
    /// Optional rather than a plain `Int` because the type has carried a destination with no digit
    /// before and will again — `MenuCommand.allCases` and `ShellCommands`' View group both filter on
    /// it, and collapsing it now would delete the filter that keeps a future digit-less destination
    /// out of the menu.
    ///
    /// **The map is the mock's since M20, and the digits are absolute rather than contiguous.**
    /// `design/mcp-router-console.html` reads Discover `⌘1`, Skills `⌘2`, Servers `⌘3`, Activity
    /// `⌘4`, Harnesses `⌘5`, Checks `⌘6`, Cleanup `⌘7`, Inbox `⌘8`, Insights `⌘9`. Harnesses and
    /// Insights are M22's and do not exist, so **`⌘5` and `⌘9` are unbound** rather than the other
    /// seven being packed into `⌘1`–`⌘7`: packing them would move every digit a user has learned on
    /// the day M22 lands, and a shortcut that moves is worse than one that is briefly missing.
    ///
    /// `PRD.md` §9.4 still lists the older order (Servers `⌘1` through Cleanup `⌘9`) and is stale
    /// against its own mock — the re-order landed at `6c513b0` on 2026-08-20, an owner-authored
    /// commit whose message states the intent, after §9.4 was written. `spec-M20.md` §2 records
    /// that as an assumption rather than a question, on the ground that reversing one table breaks
    /// nothing.
    ///
    /// **The sidebar's own order is untouched.** `ordered` is still declaration order and the two
    /// groups are still Running and Library, because regrouping the sidebar into the mock's four
    /// sections is M22's — `group` says so below. So the View menu and the sidebar list these seven
    /// in different orders until M22 lands, which is declared in `planning/fidelity/` rather than
    /// left to be discovered.
    ///
    /// **Settings is not here and does not get `⌘0`.** `DESIGN.md` §8 binds it to `⌘,`; giving it a
    /// digit too would put two shortcuts on one command, which is how a menu bar starts teaching two
    /// different habits for the same thing. M20 owns the accelerator map and granted exactly one new
    /// chord — `⌃W` — in `DESIGN.md` §8 rather than in a `switch`.
    public var selectionDigit: Int? {
        switch self {
        case .discover: 1
        case .skills: 2
        case .servers: 3
        case .activity: 4
        case .evals: 6
        case .cleanup: 7
        case .inbox: 8
        }
    }

    /// Where this destination's badge count comes from, or `nil` when it may not have one.
    ///
    /// **Skills is deliberately `nil`.** The prototype draws a badge on it and the control API
    /// serves no skills endpoint at all, so a count there would be invented.
    ///
    /// **Inbox was `nil` until M6 and is not any more.** The reason it was is recorded here because
    /// it is the reason it changed: Inbox means the phone's review queue (`DESIGN.md` §9), the
    /// router does not serve it, and until a surface actually held that queue there was nothing
    /// counting it. M6 builds the queue into the app, so the count is now an observation the app
    /// makes directly rather than a number nobody took. `heldChanges` is still not an inbox — it is
    /// one server's held tool-surface change, already counted by `needsAttention` on the Servers
    /// badge — and nothing here reads it.
    public var badgeSource: BadgeSource? {
        switch self {
        case .servers: .serversNeedingAttention
        case .cleanup: .serversNeverUsed
        case .inbox: .queuedFromPhone
        case .activity, .skills, .discover, .evals: nil
        }
    }

    /// The raw value of the `Icon` case this destination draws.
    ///
    /// A string rather than the `Icon` type itself because `Icon` lives in `MCPRouterUI` and this
    /// module must stay free of UI frameworks (`SWIFT_PRACTICES.md` §8). `ShellIconTests` in the
    /// UI module asserts every one of these resolves to a real case, so the indirection cannot
    /// silently point at nothing.
    public var iconName: String {
        switch self {
        case .activity: "activity"
        case .servers: "servers"
        case .skills: "skills"
        case .discover: "discover"
        case .inbox: "inbox"
        case .evals: "evals"
        case .cleanup: "cleanup"
        }
    }

    /// The destinations in sidebar order, which is declaration order.
    public static var ordered: [Destination] { allCases }

    /// The destinations in one group, in order.
    public static func inGroup(_ group: DestinationGroup) -> [Destination] {
        ordered.filter { $0.group == group }
    }

    /// What a stored destination restores to when this build no longer has it.
    ///
    /// `DESIGN.md` has no rule for this, but a blank pane does: restoring a name this version does
    /// not know must land somewhere real rather than rendering nothing. Activity is the first
    /// destination and the one that needs no selection to be meaningful.
    ///
    /// **This path's behaviour changed in M15 without a line of it moving**, which is what it was
    /// written for. A `UserDefaults` domain holding `shell.selectedDestination = "settings"` used to
    /// restore to the Settings board, because the case existed; the same stored value now restores
    /// to Activity, because `restoring`'s `guard let` fails.
    public static let fallback: Destination = .activity

    /// Restores a stored raw value, falling back rather than failing.
    public static func restoring(_ storedRawValue: String?) -> Destination {
        guard let storedRawValue, let destination = Destination(rawValue: storedRawValue) else {
            return fallback
        }
        return destination
    }
}
